Sync with official fan translations
Prior99/cah-fullformat-german pull request #6
Opened 2018-04-11 18:31 UTC by Vankog

implementation of #2
* Synchronizing the phrases with 
   * the officially listed fan translation PDFs from the CAH website by "Balz" and "Raphael" 
   * and the official US PDF.
* Adding comments: 
   * with contexts & known references 
   * alternative, earlier and original (i.e. by the fan translations above) translations. 
   * the official English phrases
   * Reasoning: 
      * -> easier search-ability for phrases and words for future check ups
      * -> should prevent duplicates and wrong translations
      * -> matching the official English phrases with one or more translations
* Improving translations
* Moving some phrases to other topics
* Improving line breaks
* Incorporates the card changing commit b7e627186d5f29c3085e9da4498600c4d706e97d by @AnotherStranger

2018-04-11 18:32 UTC, Vankog commented on cah-fullformat-german.tex
> +\include{categories/geschichte}
just sorted alphabetically

2018-04-11 18:35 UTC, Vankog commented on commands.tex
> +	% Black Cards %
fixing wrong comment

2018-04-12 06:26 UTC, Prior99 commented
Hi, what's the license of the official fan translations? Can we use them without mentioning?

2018-04-12 10:21 UTC, Vankog commented
1. It is the same license as the main game. Mentioning must be done.
1. I mentioned them in the README.md for this reason
1. That's one reason why I opened #5 as well

2018-04-13 08:16 UTC, Prior99 requested changes
Hey. Wow thanks for your great work, I can see that you put much effort into this. Please remove the lines as suggested by my comments and I'd be more than happy to merge this!

2018-04-13 08:16 UTC, Prior99 commented on categories/basis.tex
> +% before: zuwinken
Remove the lines with `% before`. The new translations are much better and the git history should be enough if anybody cares about the old ones.

2018-04-13 08:16 UTC, Prior99 commented on categories/basis.tex
> +% original: Glasdecke
Remove the lines with `%original`. See comment above.

2018-04-13 10:59 UTC, Vankog commented
I can see why you want to remove the "before" comments. I'll remove them.
However, I'd like to stand up for keeping the "original" ones. These are the ones from the fan translations by Ballz and Raphael. I introduced them to have a mapping. Otherwise, some of their phrases that I changed for one reason or another, might be reintroduced in the future. I'd like to prevent this from happening.
Especially, because they also added some German original phrases that don't show up in the engl. version.

2018-04-13 15:40 UTC, Prior99 commented
Sounds good!

On Fri, Apr 13, 2018, 12:59 Daniel Mönch <notifications@github.com> wrote:

> I can see why you want to remove the "before" comments. I'll remove them.
> However, I'd like to stand up for keeping the "original" ones. These are
> the ones from the fan translations by Ballz and Raphael. I introduced them
> to have a mapping. Otherwise, some of their phrases that I changed for one
> reason or another, might be reintroduced in the future. I'd like to prevent
> this from happening.
> Especially, because they also added some German original phrases that
> don't show up in the engl. version.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Prior99/cah-fullformat-german/pull/6#issuecomment-381101348>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABbCdu-l0LCEDioWgLK4gBUV4szOb7j1ks5toIUmgaJpZM4TQh69>
> .
>

2018-04-16 12:08 UTC, Vankog commented
better?

2018-04-16 12:58 UTC, merged

2018-04-16 12:58 UTC, Prior99 commented
Yes. Accepted. Thanks for your contribution :)